apiVersion: v1
kind: Service
metadata:
  name: atsea-webapp
  namespace: atsea-test
  labels:
    run: atsea-web
spec:
  type: NodePort
  ports: 
    - port: 8080
      nodePort: 33333
  selector:
    run: atsea-web