version: "3.7"

services:
  database:
    image: dtr.mydomain.com/dev/atsea_db:local
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: atsea
    networks:
      - back-tier
    secrets:
      - postgres_password

  appserver:
    image: dtr.mydomain.com/dev/atsea_app:local
    networks:
      - front-tier
      - back-tier
      - payment
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        com.docker.lb.hosts: at-sea.mydomain.com
        com.docker.lb.network: front-tier
        com.docker.lb.port: 8080
        com.docker.lb.ssl_cert: wildcard.mydomain.com.server.crt
        com.docker.lb.ssl_key: wildcard.mydomain.com.key
        
    secrets:
      - postgres_password

  payment_gateway:
    image: dtr.mydomain.com/dev/payment_gateway:local
    secrets:
      - source: staging_token
        target: payment_token
    networks:
      - payment
    deploy:
      update_config:
        failure_action: rollback

networks:
  front-tier:
    external: true
  back-tier:
    driver: overlay
  payment:
    driver: overlay
    driver_opts:
      encrypted: 'yes'

secrets:
  postgres_password:
    external: true
  staging_token:
    external: true
  wildcard.mydomain.com.key:
    external: true
  wildcard.mydomain.com.server.crt:
    external: true