version: '3.3'

services:
  
  signup-db:
    image: dtr.mydomain.com/dev/db-image:v1     
    networks:
      - app-neto
    deploy:
      endpoint_mode: dnsrr  
      placement:
        constraints:
          - node.platform.os==windows

  signup-app:
    image: dtr.mydomain.com/dev/app-image:v1
    ports:
      - mode: host
        target: 80
        published: 8000
    depends_on:
      - signup-db
    networks:
      - app-neto
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.platform.os==windows

networks:
  app-neto:
    driver: overlay