version: "3.7"

services:
  reverse_proxy:
    build: 
      context: ./reverse_proxy
    user: nginx
    image: reverse_proxy

  database:
    build: 
       context: ./database
    image: dtr.mydomain.com/dev/atsea_db:local

  appserver:
    build:
       context: app
       dockerfile: Dockerfile
    image: dtr.mydomain.com/dev/atsea_app:local

  payment_gateway:
    build:
      context: payment_gateway
    image: dtr.mydomain.com/dev/payment_gateway:local

