# atsea-web .gitlab-ci.yml
variables:
  DTR_SERVER: dtr.mydomain.com

image: docker:stable

stages:
  - build
  - test
  - push
  - deploy

before_script:
  - docker login -u builder -p $BUILDER_PW ${DTR_SERVER}

build-image:
  stage: build
  script:
    - docker image build -t ${DTR_SERVER}/dev/"${CI_PROJECT_NAME}"_build:${CI_COMMIT_REF_NAME} .
    - docker image build -t local-test-driver:${CI_PIPELINE_ID} local-test-driver

deploy-test-on-swarm:
  stage: test
  script:
    - docker stack deploy --with-registry-auth -c docker-compose-e2e.yml atsea-web-${CI_PIPELINE_ID}
    - sleep 30
    - docker container run --network atsea-web-${CI_PIPELINE_ID}_front-tier --name local-test-driver-container-${CI_PIPELINE_ID} local-test-driver:${CI_PIPELINE_ID}
  after_script:
    - docker stack rm atsea-web-${CI_PIPELINE_ID}
    - docker container rm -f local-test-driver-container-${CI_PIPELINE_ID}
    - docker image rm local-test-driver:${CI_PIPELINE_ID}

push-branch:
  stage: push
  script:
    - docker push $DTR_SERVER/dev/"${CI_PROJECT_NAME}"_build:${CI_COMMIT_REF_NAME}

push-master:
  stage: push
  script:
    - docker image tag  $DTR_SERVER/dev/"${CI_PROJECT_NAME}"_build:${CI_COMMIT_REF_NAME} $DTR_SERVER/dev/"${CI_PROJECT_NAME}"_build:RC-DEV
    - docker image push $DTR_SERVER/dev/"${CI_PROJECT_NAME}"_build:RC-DEV 
    - docker image rm   $DTR_SERVER/dev/"${CI_PROJECT_NAME}"_build:RC-DEV 
  only:
  - master

deploy-to-test:
  stage: deploy
  before_script:
    - apk add curl  
  script:
    - echo "wait for test image promotion..."
    - sleep 10
    - curl -X POST -F token=${DEPLOY_TRIGGER_TOKEN} -F "ref=master" -F "variables[DEPLOY_TARGET]=test" https://gitlab.com/api/v4/projects/10552558/trigger/pipeline