apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: atsea-test
  labels:
    run: atsea-database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: http
  selector:
    run: atsea-database